services:
  - type: web
    name: nexus-social
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run db:push && npm run start
    healthCheckPath: /login
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
